runs:
  using: "composite"
  steps:
    - name: "checkout repository"
      uses: actions/checkout@v3

    - name: "setup node"
      uses: actions/setup-node@v3
      with:
        node-version: 18
      
    - name: "install dependencies"
      uses: bahmutov/npm-install@v1

    - name: 'create env file for API keys'
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env