version: '3.9'
services:
  nginx:
    container_name: vuejs-api-demo-1
    image: index.docker.io/lucasschmitz/vuejs-api-demo:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - /data/certbot/letsencrypt:/etc/letsencrypt
        - /data/certbot/www:/var/www/certbot