version: '3.9'
services:
  certbot:
    container_name: certbot-1
    image: certbot/certbot:v1.8.0
    volumes:
      - /data/certbot/letsencrypt:/etc/letsencrypt
      - /data/certbot/www:/tmp/letsencrypt
    command: certonly --webroot -w /tmp/letsencrypt --email mrlucas.schmitz@aol.de -d schmitz.berlin -d www.schmitz.berlin --agree-tos --verbose --keep-until-expiring --preferred-challenges=http --cert-name schmitz.berlin