version: '3.3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'apiproject'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'PASSWORD!!!'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - /data/mysql:/var/lib/mysql
    container_name: mysqldb