name: Develop

on: 
  push:

  workflow_dispatch:

jobs:
  lint:
    runs-on: [self-hosted]
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: "install dependencies"
        uses: bahmutov/npm-install@v1
      
      - name: "linting"
        run: "echo 'linting...'"

  test:
    runs-on: [self-hosted]
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: "install dependencies"
        uses: bahmutov/npm-install@v1
      
      - name: "testing"
        run: "echo 'testing...'"

  build:
    runs-on: [self-hosted]
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: "install dependencies"
        uses: bahmutov/npm-install@v1
      
      - name: "build application"
        run: npm run build
