name: Develop

on: push

jobs:
  lint:
    runs-on: [self-hosted]
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: "install dependencies"
        uses: bahmutov/npm-install@v1

  test:
    runs-on: [self-hosted]
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: "install dependencies"
        uses: bahmutov/npm-install@v1
