name: Develop

on: push

jobs:
  lint:
    runs-on: [self-hosted]
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "test node"
        run: node --version
        run: npm --version
