name: Lint-Test-Build

on: push

jobs:
  Lint:
    runs-on: [self-hosted]
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: select frontend folder
        run: cd frontend
      
      - name: "install dependencies"
        uses: bahmutov/npm-install@v1
        with: 
          working-directory: frontend

      - name: 'create env file for API keys'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      
      - name: "linting"
        run: npm run lint

  Test:
    runs-on: [self-hosted]
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: select frontend folder
        run: cd frontend
      
      - name: "install dependencies"
        uses: bahmutov/npm-install@v1
        with: 
          working-directory: frontend

      - name: 'create env file for API keys'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      
      - name: "run cypress tests"
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: npm run dev
          wait-on: "http://localhost:8080"
          wait-on-timeout: 110
          config-file: cypress.config.ts
          command: npm run cy:run

      - name: Archive code coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: CodeCoverage
          path: reports
          retention-days: 14

  Build:
    runs-on: [self-hosted]
    needs: [Lint, Test]
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: select frontend folder
        run: cd frontend
      
      - name: "install dependencies"
        uses: bahmutov/npm-install@v1
        with: 
          working-directory: frontend
      
      - name: 'create env file for API keys'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      
      - name: "build application"
        run: npm run build-only

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BuildWebApp
          path: dist
          retention-days: 14
