name: Lint-Test-Build

on: push

jobs:
  Lint:
    runs-on: [self-hosted]
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: "install dependencies"
        uses: bahmutov/npm-install@v1
      
      - name: "linting"
        run: "echo 'linting...'"

  Test:
    runs-on: [self-hosted]
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: "install dependencies"
        uses: bahmutov/npm-install@v1
      
      - name: "testing"
        run: "echo 'testing...'"

  Build:
    runs-on: [self-hosted]
    needs: [Lint, Test]
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: "install dependencies"
        uses: bahmutov/npm-install@v1
      
      - name: 'create env file for API keys'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      
      - name: "build application"
        run: npm run build-only

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: BuildWebApp
          path: dist
          retention-days: 14
